In [252]:
import os
import zipfile
import pandas as pd
from urllib import request

In [ ]:
# Get data from 'World Development Indicators' dataset

In [243]:
country_code = ['BOL','CRI','DMA','SLV','GUY','PAN','URY','SUR','ARG','BRA','CHL','MEX','PRY','BLZ','COL','ECU','GTM','HND','NIC','PER','KOR'] # Latin America(LCN) + South Korea

In [351]:
class API_DOWNLOADER():

    def __init__(self, INDICATOR, FILE_DIR):
        
        self.ctr = 'BOL;CRI;DMA;SLV;GUY;PAN;URY;SUR;ARG;BRA;CHL;MEX;PRY;BLZ;COL;ECU;GTM;HND;NIC;PER;KOR'
        self.idct = INDICATOR
        self.folder =  f'{FILE_DIR}/downloads'
        self.dir = f'{self.folder}/{self.idct}'
    def api_download(self):
        
        try:
            os.makedirs(f'{self.folder}')      
        except:
            pass
        
        url = f'http://api.worldbank.org/v2/country/{self.ctr}/indicator/{self.idct}/?source=2&downloadformat=csv&dataformat=table'
        zip_file = f'{self.dir}.zip'
        request.urlretrieve(url, zip_file)
        
        with zipfile.ZipFile(zip_file, 'r') as z:
            z.extractall(f'{self.dir}')
        
        print('Download Done')
        
    
    def change_csv_file_name(self): 
    
        names = os.listdir(f'{self.dir}')
        os.rename(f'{self.dir}/{names[0]}', f'{self.dir}/{self.idct}.csv')

In [352]:
indicator = 'AG.AGR.TRAC.NO'
file_dir = './test'

downloader = API_DOWNLOADER(indicator, file_dir)

downloader.api_download()

Download Done

In [353]:
downloader.change_csv_file_name()

In [251]:
df = pd.read_csv('test\API_Download_DS2_EN_csv_v2_3979070.csv', header=2)
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Argentina,ARG,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,120000,130000,140000,150000,155000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Belize,BLZ,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,211,269,314,402,400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bolivia,BOL,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,1300,1400,1500,1600,1700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Brazil,BRA,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,72000,82000,93000,103000,114000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Chile,CHL,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,33550,33600,33650,33700,33750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Colombia,COL,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,18241,19251,20380,20125,20535,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Costa Rica,CRI,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,3800,4200,4454,4500,4600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Dominica,DMA,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,28,32,32,36,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ecuador,ECU,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,1558,1565,1620,1700,2000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Guatemala,GTM,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,1950,2100,2250,2400,2550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Guyana,GUY,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,3240,3250,3260,3270,3280,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Honduras,HND,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,304,307,309,340,395,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"Korea, Rep.",KOR,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,24,24,24,30,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Mexico,MEX,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,56000,60000,64000,68000,72000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Nicaragua,NIC,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,130,150,180,200,250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Panama,PAN,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,347,550,800,1000,1250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Peru,PER,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,6950,7385,7700,8000,8500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Paraguay,PRY,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,3900,4000,4100,4200,4300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,El Salvador,SLV,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,1600,1650,1700,1750,1800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Suriname,SUR,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,580,590,600,730,760,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Uruguay,URY,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,NaN,24695,25330,25960,26590,27220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN